POST http://localhost:3000/tournaments HTTP/1.1
content-type: application/json

{
  "name": "Evolution Tournament 1",
  "discipline": "Yu-Gi-Oh!",
  "format": "SINGLE_ELIMINATION",
  "status": "PUBLISHED",
  "allowMixedParticipants": false,
  "participantType": "PLAYER",
  "maxParticipants": 8
}