POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Yugi Muto",
  "nickname": "KingOfGames",
  "countryCode": "JP"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Joey Wheeler",
  "metadata": {
    "position": 1
  }
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Seto Kaiba"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Mai Valentine",
  "metadata": "harpie lady"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Tea Gardner"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Yami Yugi"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Yami Bakura",
  "metadata": "metadata"
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Yami Ishtar",
  "metadata": {
    "hello": "world"
  }
}

POST http://localhost:3000/players HTTP/1.1
content-type: application/json

{
  "displayName": "Rex Raptor",
  "metadata": "metadata"
}